-- No database required — this is a static portfolio site.
-- All functionality (including contact form) is handled by frontend and Vercel serverless functions.
-- Supabase is used only for potential future feature expansion; no tables, storage buckets, or edge functions are needed at launch.